# Generated by Django 4.1.7 on 2024-03-30 08:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('date_joined', models.DateField(auto_now_add=True, null=True, verbose_name='Joined time')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('vat', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('delivery_cost', models.IntegerField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('product_varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.varient')),
                ('usersales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_info.customer_info')),
            ],
        ),
    ]
