# Generated by Django 5.0.3 on 2024-04-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='curierInvoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
