# Generated by Django 5.0.3 on 2024-04-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_curierinvoice_customer_courierinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesreturn',
            old_name='date',
            new_name='return_date',
        ),
    ]
